/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ide245;

import java.io.File;
import java.io.IOException;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author m10kaa
 */
public class LScreen extends javax.swing.JFrame {

    /**
     * Creates new form LScreen
     */
    public LScreen(JFrame frame) {
        try {
            img = new ImageIcon(ImageIO.read(new File("screen.jpg")));
        } catch (IOException ex) {
            Logger.getLogger(LScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
        f = frame;
        initComponents();
        dispose();
        setUndecorated(true);
        setSize(440, 400);
        setVisible(true);
        this.setLocationRelativeTo(null); 
        setContentPane(new JLabel(img));
        getLayeredPane().add(jProgressBar1);
        getLayeredPane().add(jLabel1);
        Timer t = new Timer();
        Refresher r = new Refresher();
        t.schedule(r, 0, 1);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusable(false);
        setFocusableWindowState(false);
        setForeground(java.awt.Color.white);
        setPreferredSize(new java.awt.Dimension(560, 480));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jProgressBar1.setMaximum(10000);
        jProgressBar1.setFocusable(false);
        getContentPane().add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 440, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Loading ...");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 440, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables


    private ImageIcon img;
    private JFrame f;
    
    private class Refresher extends TimerTask {

        @Override
        public void run() {
            int value = jProgressBar1.getValue();
            String s = "";
            value += inc;
            if (value == 10000) {
                cancel();
                setVisible(false);
                f.setVisible(true);
            } else if (value > 7500) {
                s = "Reading thoughts...";
            } else if (value > 5000) {
                s = "Selling info to the black market...";
                inc = 6;
                if (value > 7000)
                    inc = 2;
            } else if (value > 2500) {
                s = "Hacking Pentagon...";
                inc = 4;
                if (value > 3500)
                    inc = 6;
            } else 
                s = "Connecting to satellite...";
            jLabel1.setText(s);
            jProgressBar1.setValue(value);
        }
        
        private int inc = 4;
    }
}
